site_name: LePub
site_author: Mikkel Roald-Arbøl
site_url: https://lapreprint.github.io/lepub
repo_url: https://github.com/lapreprint/lepub
repo_name: lapreprint/lepub
copyright: Copyright &copy; 2025 Maintained by <a href="https://github.com/roaldarbol">Mikkel Roald-Arbøl</a>.
nav:
  - Home: index.md
  # - Typst:
  #   - Quick start: typst.md
  #   - Settings:
  #     - Front matter: frontmatter-typst.md
  #     - Options: options-typst.md
  # - Quarto:
  #   - Quick start: quarto.md
  #   - Settings:
  #     - Front matter: frontmatter-quarto.md
  #     - Options: options-quarto.md
  # - MyST:
  #   - Quick start: myst.md
  #   - Settings:
  #     - Front matter: frontmatter-myst.md
  #     - Options: options-myst.md
  - Quick start:
    - With Typst: typst.md
    - With Quarto: quarto.md
    - With MyST: myst.md
    - With Word: docx.md
  - Settings:
    - Typst:
      - "Typst: Front matter": frontmatter-typst.md
      - "Typst: Options": options-typst.md
    - Quarto:
      - "Quarto: Front matter": frontmatter-quarto.md
      - "Quarto: Options": options-quarto.md
    - MyST: 
      - "MyST: Front matter": frontmatter-myst.md
      - "MyST: Options": options-myst.md
    - Word:
      - "Word: Front matter": frontmatter-docx.md
      - "Word: Options": options-docx.md
  - Build Your Own:
    - Overview: overview.md
    - Theming: defaults.md
    - Quarto & MyST: edit-quarto-myst.md
    - Documentation: docs.md
    - Share: share.md
theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.footer
    - toc.integrate
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list

plugins:
  - search
  - git-revision-date-localized

extra_css:
  - stylesheets/extra.css