[workspace]
authors = ["Mikkel Roald-Arbøl <github.ggb9a@simplelogin.co>"]
channels = ["conda-forge"]
name = "LePub"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]
copy-to-typst = "cp lepub.typ typst/1.0.0"
copy-to-quarto = "cp lepub.typ quarto/_extensions/lepub"
copy-to-myst = "cp lepub.typ myst/lepub"
copy = { depends-on = ["copy-to-typst", "copy-to-quarto", "copy-to-myst"] }
render-typst = { cmd = "typst compile typst/1.0.0/template/from-yaml.typ --root ..", depends-on = "copy" }
render-quarto = { cmd = "quarto render quarto/example.qmd", depends-on = "copy" }
render-myst = { cmd = "myst build myst/example.md", depends-on = "copy" }

[tasks.new-name]
args = ["new-name"]
cmd = "find -type f ( -name \"*.md\" -o -name \"*.qmd\" -o -name \"*.yaml\" -o -name \"*.typ\" -o -name \"*.toml\" -o ) -exec grep -l \"lepub\" {} ; | xargs sed -i \"s/lepub/{{ new-name }}/g\""

[dependencies]
typst = ">=0.13.1,<0.14"
mystmd = ">=1.3.25,<2"
imagemagick = ">=7.1.1_47,<8"
# quarto = ">=1.7.0,<2"
