[workspace]
authors = ["Mikkel Roald-Arbøl <github.ggb9a@simplelogin.co>"]
channels = ["conda-forge"]
name = "LePub"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]
copy-to-typst = "cp lepub.typ typst/1.0.0"
copy-to-quarto = "cp lepub.typ quarto/_extensions/lepub"
copy-to-myst = "cp lepub.typ myst/lepub"
copy-to-docx = "cp lepub.typ docx"
copy = { depends-on = ["copy-to-typst", "copy-to-quarto", "copy-to-myst", "copy-to-docx"] }
render-typst = { cmd = "typst compile typst/1.0.0/template/from-manual.typ --root ..", depends-on = "copy" }
render-quarto = { cmd = "quarto render quarto/example.qmd", depends-on = "copy" }
render-myst = { cmd = "myst build myst/example.md", depends-on = "copy" }
render-docx-pre = { cmd = "pandoc -f docx -t typst docx/test.docx --template=docx/docx-show.typ --lua-filter=docx/filters/docx-custom-properties.lua --lua-filter=docx/filters/docx-keywords.lua -o docx/test.typ", depends-on = "copy-to-docx"}
render-docx = { cmd = "typst compile docx/test.typ", depends-on = "render-docx-pre" }
render-all = { depends-on = ["render-typst", "render-quarto", "render-myst", "render-docx"]}

[tasks.rename]
args = ["new-name"]
cmd = "find . -type f -name \"*.md\" -o -name \"*.qmd\" -o -name \"*.yaml\" -o -name \"*.typ\" -o -name \"*.toml\" | xargs -I{} sh -c 'if grep -q \"lepub\" {}; then sed -i \"s/lepub/{{ new-name }}/g\" {}; echo \"Updated: {}\"; fi'"

[dependencies]
typst = ">=0.13.1,<0.14"
imagemagick = ">=7.1.1_47,<8"
mkdocs-material = ">=9.6.12,<10"
mystmd = ">=1.3.25,<2"
mkdocs-git-revision-date-localized-plugin = ">=1.2.9,<2"
pandoc = ">=3.6.4,<4"
# quarto = ">=1.7.0,<2"
